import Articles from "components/ArticleItem";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";

import { api } from "utils/lib";

interface Props {
  posts: any;
}

const Home: NextPage<Props> = ({ posts }) => {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-wrap justify-between">
        {posts.map((post: any, index: string) => (
          <>
            <Articles key={index} post={post} />
          </>
        ))}
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = (context) => {
  const articles = api.getAllArticles([
    "slug",
    "title",
    "description",
    "date",
    "coverImage",
    "excerpt",
    "timeReading",
    "cover",
    "tags",
  ]);
  return { props: { posts: articles } };
};
export default Home;
