import type { NextPage } from "next";

import Head from "next/head";

import Transition from "components/Transition";
import Hero from "components/Hero";
import About from "components/About";
import Contact from "components/Contact";
import Socials from "components/Socials";

const Home: NextPage = () => {
  return (
    <Transition id="home">
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
        <About />
        <Contact />
        <Socials />
      </div>
    </Transition>
  );
};

export default Home;
